#!/bin/bash

# Optimizing configuration loading, route loading and view loading
# https://laravel.com/docs/9.x/deployment#optimization


composer install --ignore-platform-reqs
npm install
npm run build
php artisan migrate --force
php artisan config:clear
php artisan route:cache
php artisan view:cache
