#!/bin/bash

# Optimizing configuration loading, route loading and view loading
# https://laravel.com/docs/9.x/deployment#optimization


php artisan migrate --force

composer install --ignore-platform-reqs

php artisan config:clear

php artisan route:cache

php artisan view:cache
